language: java
install: mkdir lib
install: wget -O lib/junit-4.12.jar "http://search.maven.org/remotecontent?filepath=junit/junit/4.12/junit-4.12.jar"
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
